Document: ddeskshell
Title: Debian ddeskshell Manual
Author: <insert document author here>
Abstract: This manual describes what ddeskshell is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ddeskshell/ddeskshell.sgml.gz

Format: postscript
Files: /usr/share/doc/ddeskshell/ddeskshell.ps.gz

Format: text
Files: /usr/share/doc/ddeskshell/ddeskshell.text.gz

Format: HTML
Index: /usr/share/doc/ddeskshell/html/index.html
Files: /usr/share/doc/ddeskshell/html/*.html
